import { NextRequest,NextResponse } from 'next/server';
import crypto from 'node:crypto';
import { read,update } from '@/lib/storage';
import { APPS,MESSAGES,makeRecipients } from '@/lib/message-manager';
import { cleanText } from '@/lib/validation';
import { rateLimit } from '@/lib/rate-limit';
import { sendMessage } from '@/lib/message-manager';
import type { FirebaseApp,Message } from '@/lib/types';
export const runtime='nodejs';
export async function GET(){try{return NextResponse.json({success:true,data:await read<Message[]>(MESSAGES)})}catch{return NextResponse.json({success:false,error:'Unable to read message history'},{status:500})}}
export async function POST(request:NextRequest){if(!rateLimit(request.headers.get('x-forwarded-for')||'local',8))return NextResponse.json({success:false,error:'Too many message requests. Try again shortly.'},{status:429});try{const body=await request.json();const title=cleanText(body.title,'Title',120);const messageBody=cleanText(body.body,'Message body',2000);const targetType=body.targetType==='token'?'token':'topic';const targetValue=cleanText(body.targetValue||'all',targetType==='token'?'Device token':'Topic',2000);const ids=Array.isArray(body.appIds)?[...new Set(body.appIds.filter((id:any)=>typeof id==='string'))]:[];if(!ids.length)throw new Error('Select at least one Firebase app');const apps=(await read<FirebaseApp[]>(APPS)).filter(app=>ids.includes(app.id)&&app.isActive);if(!apps.length)throw new Error('Selected apps are unavailable or inactive');if(targetType==='token'&&apps.length!==1)throw new Error('Send to a device token with exactly one Firebase app selected; tokens are app-specific.');const now=new Date().toISOString();const scheduledTime=body.scheduledTime?new Date(body.scheduledTime).toISOString():undefined;if(scheduledTime&&Date.parse(scheduledTime)<=Date.now())throw new Error('Schedule time must be in the future');const messageId=crypto.randomUUID();const isDraft=body.intent==='draft';const message:Message={id:messageId,title,body:messageBody,messageType:body.messageType==='data'?'data':'notification',targetType,targetValue,...(body.imageUrl?{imageUrl:cleanText(body.imageUrl,'Image URL',1000)}:{}),...(body.data&&typeof body.data==='object'?{data:Object.fromEntries(Object.entries(body.data).slice(0,30).map(([key,value])=>[String(key).slice(0,100),String(value).slice(0,1000)]))}:{}),...(scheduledTime?{scheduledTime,timezone:typeof body.timezone==='string'?body.timezone:'UTC'}:{}),sendImmediately:!scheduledTime&&!isDraft,status:scheduledTime?'scheduled':'draft',totalAppsTargeted:apps.length,totalSent:0,totalFailed:0,appIds:apps.map(app=>app.id),recipients:makeRecipients(messageId,apps),createdAt:now,updatedAt:now};await update<Message[]>(MESSAGES,items=>[message,...items]);const result=scheduledTime||isDraft?message:await sendMessage(messageId);return NextResponse.json({success:true,data:result},{status:201})}catch(error){return NextResponse.json({success:false,error:(error as Error).message||'Unable to create message'},{status:400})}}
